---
version: '3.4'

services:
  jekyll:
    image: glenux-blog:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: foreman start
    volumes:
      - .:/app
      - jekyll_cache:/app/.jekyll-cache/
    ports:
      - "8000:80"

volumes:
  jekyll_cache: {}
